package com.server.goods;

public enum GoodsCate {
	GOODSBEAN, STONEBEAN, BLUEPRINTPIECEBEAN, BLUEPRINTBEAN, TOWERBEAN, MONSTERBEAN, 
	MATERIALBEAN, SLAVERBEAN, CASTLEBEAN, CITYBEAN, PROPBEAN, TIMESBEAN, RACE, TITLEBEAN ,
	PRIZEBEAN, TASKBEAN, INDEXBEAN, SOULTOWERBEAN, MINEBEAN, TECHNOLOGYTOWERBEAN, TECHNOLOGYTREEBEAN,
	TREASURECHESTBEAN
}
