//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4959
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleGame {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleGame.zh-cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 C# 的本地化字符串。
        /// </summary>
        internal static string CSharp {
            get {
                return ResourceManager.GetString("CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	 的本地化字符串。
        /// </summary>
        internal static string tab {
            get {
                return ResourceManager.GetString("tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        internal static string 主菜单 {
            get {
                return ResourceManager.GetString("主菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要退出当前游戏吗？ 的本地化字符串。
        /// </summary>
        internal static string 你确定要退出当前游戏吗 {
            get {
                return ResourceManager.GetString("你确定要退出当前游戏吗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要退出游戏吗 的本地化字符串。
        /// </summary>
        internal static string 你确定要退出游戏吗 {
            get {
                return ResourceManager.GetString("你确定要退出游戏吗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏 的本地化字符串。
        /// </summary>
        internal static string 全屏 {
            get {
                return ResourceManager.GetString("全屏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        internal static string 关 {
            get {
                return ResourceManager.GetString("关", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单峰骆驼 的本地化字符串。
        /// </summary>
        internal static string 单峰骆驼 {
            get {
                return ResourceManager.GetString("单峰骆驼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去氧核糖核酸 的本地化字符串。
        /// </summary>
        internal static string 去氧核糖核酸 {
            get {
                return ResourceManager.GetString("去氧核糖核酸", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双峰骆驼 的本地化字符串。
        /// </summary>
        internal static string 双峰骆驼 {
            get {
                return ResourceManager.GetString("双峰骆驼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喜欢的动物 的本地化字符串。
        /// </summary>
        internal static string 喜欢的动物 {
            get {
                return ResourceManager.GetString("喜欢的动物", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        internal static string 年龄 {
            get {
                return ResourceManager.GetString("年龄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        internal static string 开 {
            get {
                return ResourceManager.GetString("开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        internal static string 开始游戏 {
            get {
                return ResourceManager.GetString("开始游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果 的本地化字符串。
        /// </summary>
        internal static string 效果 {
            get {
                return ResourceManager.GetString("效果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停游戏 的本地化字符串。
        /// </summary>
        internal static string 暂停游戏 {
            get {
                return ResourceManager.GetString("暂停游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在载入... 的本地化字符串。
        /// </summary>
        internal static string 正在载入 {
            get {
                return ResourceManager.GetString("正在载入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        internal static string 法语 {
            get {
                return ResourceManager.GetString("法语", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string 确定 {
            get {
                return ResourceManager.GetString("确定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string 语言 {
            get {
                return ResourceManager.GetString("语言", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string 返回 {
            get {
                return ResourceManager.GetString("返回", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回游戏 的本地化字符串。
        /// </summary>
        internal static string 返回游戏 {
            get {
                return ResourceManager.GetString("返回游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出游戏 的本地化字符串。
        /// </summary>
        internal static string 退出游戏 {
            get {
                return ResourceManager.GetString("退出游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置选项 的本地化字符串。
        /// </summary>
        internal static string 配置选项 {
            get {
                return ResourceManager.GetString("配置选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 骆驼 的本地化字符串。
        /// </summary>
        internal static string 骆驼 {
            get {
                return ResourceManager.GetString("骆驼", resourceCulture);
            }
        }
    }
}
